rcon:
  host: "127.0.0.1"
  port: 25575
  password: "change_me"

refresh_rate: 30

page_title: "Score Rankings"

scores:
  - key: kill
    title: "KILL RANKING"
    sort: 0
    time: false
  - key: damage
    title: "DAMAGE RANKING"
    sort: 1
    time: false