rcon:
  host: "127.0.0.1"
  port: 25575
  password: "change_me"
  timeout: 3

# 0で自動更新しない
refresh_rate: 30

page_title: "Score Rankings"

# 0で降順
scores:
  - key: kill
    title: "KILL RANKING"
    sort: 0
    time: false
  - key: damage
    title: "DAMAGE RANKING"
    sort: 1
    time: false