rcon:
  host: "127.0.0.1"
  port: 25575
  password: "change_me"

# 自動更新のインターバル[秒]、0にすると無効
refresh_rate: 30

page_title: "Score Rankings"

# 0:降順, 1:昇順
scores:
  - key: kill
    title: "KILL RANKING"
    sort: 0
  - key: damage
    title: "DAMAGE RANKING"
    sort: 1